Added Logout Route in Admin API
Deveimer/vovoca-backend pull request #3
Opened 2023-05-26 16:51 UTC by abhijeetnishal

Closes #1 

Implemented the logout functionality and logout route in Admin API.

2023-05-26 17:52 UTC, varun-singhh requested changes

2023-05-26 17:52 UTC, varun-singhh commented on controllers/adminController.js
> +  },
response message in json should be small, and no special chars. `user logged out`

2023-05-26 17:57 UTC, abhijeetnishal commented
Hey @varun-singhh I fixed the json typo.

2023-05-27 08:31 UTC, kaustubhai approved these changes

2023-05-27 08:32 UTC, kaustubhai commented
@abhijeetnishal you can also implement this route on frontend if you want, lmk if you will be doing it

2023-05-27 09:07 UTC, abhijeetnishal commented
@kaustubhai Ok I will implement this on frontend also.

2023-05-27 19:43 UTC, varun-singhh approved these changes

2023-05-27 19:45 UTC, varun-singhh approved these changes

2023-05-27 19:46 UTC, merged